# syntax=docker/dockerfile:1

FROM nginx:1.28.2-alpine

ARG APP_DIST

ENV MFE_ALLOWED_ORIGIN=https://mfe.diidenis.com.br

COPY infra/nginx/default.conf.template /etc/nginx/templates/default.conf.template
COPY ${APP_DIST}/ /usr/share/nginx/html/

EXPOSE 80

HEALTHCHECK --interval=5s --timeout=3s --retries=12 \
  CMD wget --quiet --output-document=/dev/null http://127.0.0.1/ || exit 1
