storage: /verdaccio/storage

web:
  title: Micro Frontends Lab Registry

auth:
  htpasswd:
    file: /verdaccio/storage/htpasswd
    max_users: -1

uplinks:
  npmjs:
    url: https://registry.npmjs.org/

packages:
  '@mfe-lab/*':
    access: $all
    publish: $all
    unpublish: $all

  '**':
    access: $all
    publish: $authenticated
    unpublish: $authenticated
    proxy: npmjs

middlewares:
  audit:
    enabled: false

log:
  type: stdout
  format: pretty
  level: http
